// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAssignmentMVC.Models.Person.Data;

namespace WebAssignmentMVC.Migrations
{
    [DbContext(typeof(PersonDBContext))]
    [Migration("20220514095827_SeedPerson")]
    partial class SeedPerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAssignmentMVC.Models.Person.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryFiD")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryFiD");

                    b.HasIndex("PersonId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryFiD = 1,
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 2,
                            CountryFiD = 1,
                            Name = "Helsingborg"
                        },
                        new
                        {
                            Id = 3,
                            CountryFiD = 1,
                            Name = "Växjö"
                        },
                        new
                        {
                            Id = 4,
                            CountryFiD = 1,
                            Name = "Gävle"
                        },
                        new
                        {
                            Id = 5,
                            CountryFiD = 1,
                            Name = "Trollhättan"
                        },
                        new
                        {
                            Id = 6,
                            CountryFiD = 3,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 7,
                            CountryFiD = 3,
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 8,
                            CountryFiD = 3,
                            Name = "Munich"
                        });
                });

            modelBuilder.Entity("WebAssignmentMVC.Models.Person.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WebAssignmentMVC.Models.Person.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CtyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("WebAssignmentMVC.Models.Person.City", b =>
                {
                    b.HasOne("WebAssignmentMVC.Models.Person.Country", "Countries")
                        .WithMany("Cities")
                        .HasForeignKey("CountryFiD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAssignmentMVC.Models.Person.Person", null)
                        .WithMany("City")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("WebAssignmentMVC.Models.Person.Country", b =>
                {
                    b.HasOne("WebAssignmentMVC.Models.Person.Person", null)
                        .WithMany("Country")
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
